name: Lint Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v6

      - name: Run actionlint
        uses: rhysd/actionlint@v1.7.12
